version: '2'
services:
    toolboxapi-app:
        image: toolboxapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://toolboxapi-mysql:3306/toolboxapi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    toolboxapi-mysql:
        extends:
            file: mysql.yml
            service: toolboxapi-mysql
